### ISSUE TITLE
`clusternator describe-services` breaks

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#231] opened 2016-02-01 19:52 UTC
```
TypeError: cn.describeProject is not a function
    at /Users/rafy/Documents/rangle/the-clusternator/lib/api/0.1/cli/cloud-service.js:24:15
    at _fulfilled (/Users/rafy/Documents/rangle/the-clusternator/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/rafy/Documents/rangle/the-clusternator/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/rafy/Documents/rangle/the-clusternator/node_modules/q/q.js:796:13)
    at /Users/rafy/Documents/rangle/the-clusternator/node_modules/q/q.js:604:44
    at runSingle (/Users/rafy/Documents/rangle/the-clusternator/node_modules/q/q.js:137:13)
    at flush (/Users/rafy/Documents/rangle/the-clusternator/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:417:9)
    at process._tickDomainCallback (node.js:387:13)
```

**Comment by bennett000** [comment] 2016-02-01 19:53
That's referencing the JavaScript API... is that function missing?  Sorry I can't get my IDE open for a few hours (training)

**Comment by bennett000** [comment] 2016-02-01 19:59
This is super minor, but it needs to be plugged in.

The code in `cloud-services` should really be pointing to `cn.describeServices`.  This feature doesn't have the nicest output IIRC.  We _might_ consider deprecating it. 

Thoughts? 

Also @rafkhan what were you trying to do with this in the first place?

**Comment by bennett000** [comment] 2016-02-02 15:05
In the current master branch this should work with AWS credentials.  Currently there are no routes for it to work with the Clusternator API, but we can change that today.

I'm going to move this to done since the issue is resolved with AWS, and the CLI/Clusternator part can be covered by the as yet undone CLI mapping issue #133 

@rafkhan if you need to list services for the purposes of solving #160 you should be doing all that work within the `aws` folder, and with commands from in that section of the codebase.  If you need clarification please let me know.

**Closed** 2016-02-23 22:11 UTC
Labels: bug
